# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Capact < Formula
  desc "Capact CLI is a command-line tool, which manages Capact resources."
  homepage "https://github.com/capactio/homebrew-tap"
  version "0.7.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/capactio/capact/releases/download/v0.7.0/capact-darwin-arm64"
      sha256 "312bb0ba6bfa66f41dcdd3a189d73ec23e8bc12118454bc7bae54b20ede68d0c"

      def install
        bin.install "capact-darwin-arm64" => "capact"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/capactio/capact/releases/download/v0.7.0/capact-darwin-amd64"
      sha256 "76935b1a0575e6f05829af9a85a6237972dad9e860054a1e143c631eeb018091"

      def install
        bin.install "capact-darwin-amd64" => "capact"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/capactio/capact/releases/download/v0.7.0/capact-linux-amd64"
      sha256 "305edf06b4a3e57c0173c5a9e065cf60e2b8793f1508bad09f866c63846e7530"

      def install
        bin.install "capact-linux-amd64" => "capact"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/capactio/capact/releases/download/v0.7.0/capact-linux-arm64"
      sha256 "381a66cadfccf3682c4c32f5e58ab16d56a6e1b6bbaa9dd01c9b7a3eaecd12c9"

      def install
        bin.install "capact-linux-arm64" => "capact"
      end
    end
  end

  test do
    system "#{bin}/capact version"
  end
end
