# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Populator < Formula
  desc "Populator is a command-line tool, which helps to populate various Capact content."
  homepage "https://github.com/capactio/homebrew-tap"
  version "0.7.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/capactio/capact/releases/download/v0.7.0/populator-darwin-arm64"
      sha256 "aab28158525f0e516336d4483888c2ecc060e2b09fee3c6856093cf0a4d976b8"

      def install
        bin.install "populator-darwin-arm64" => "populator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/capactio/capact/releases/download/v0.7.0/populator-darwin-amd64"
      sha256 "b5b2d99d6561cb5bdfd1dbdf0a7bf8f9c7b57cd6499701653413ee906a7518f9"

      def install
        bin.install "populator-darwin-amd64" => "populator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/capactio/capact/releases/download/v0.7.0/populator-linux-amd64"
      sha256 "e24234798e2323767596b56d34e6bff6e27ebad9764d4726036d769f37a50a80"

      def install
        bin.install "populator-linux-amd64" => "populator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/capactio/capact/releases/download/v0.7.0/populator-linux-arm64"
      sha256 "dd3e721ca7cf96a65d3120656a5a8bd32c6c327ab653924d78a77f265615360d"

      def install
        bin.install "populator-linux-arm64" => "populator"
      end
    end
  end

  test do
    system "#{bin}/populator help"
  end
end
